
spring:
  application:
    name: Eureka_Server

server:
  port: 8181

eureka:
  instance:
    hostname: localhost
  client:
    #register-with-eureka: false
    #fetch-registry: false
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
